addons:
  apt:
    packages:
      - openjdk-6-jdk

language: java
jdk: openjdk6

branches:
  only: wicket6.x

script: mvn clean install -q
 
after_success: mvn deploy -q --settings settings.xml -P snapshot 

